// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
"use client";
import localFont from "next/font/local";
import { usePathname } from 'next/navigation'; // Use usePathname to get the current path
import AdminLayout from "./Layout/AdminLayout"; // Adjust the path as per your project structure
import AuthLayout from "./Layout/AuthLayout";  // Adjust the path as per your project structure
import "./globals.css"; // Global styles

// Custom fonts
const geistSansss = localFont({
  src: "./assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMonooo = localFont({
  src: "./assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the app
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Get current route

  // Determine if the route is for authentication
  const isAuthRoute = ["/signin", "/signup", "/password-reset", "/two-step", "/lockscreen", "/maintenance", "/404"].includes(pathname);

  return (
    <html lang="en">
      <body>
        {isAuthRoute ? (
          // Render AuthLayout for authentication-related routes
          <AuthLayout>
            {children}
          </AuthLayout>
        ) : (
          // Render AdminLayout for other routes
          <AdminLayout>
            {children}
          </AdminLayout>
        )}
      </body>
    </html>
  );
}
